{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ucscxenashiny
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/UCSCXenaShiny_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/UCSCXenaShiny/UCSCXenaShiny_{{ version }}.tar.gz
  sha256: be997996573590e8dac312996d7d24705402b9536a2c5ec282c3a94e139b3688

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - gmp   # [linux]
    - mpfr  # [linux]
    - r-base
    - r-digest
    - r-dplyr >=0.8.3
    - r-ezcox
    - r-forcats
    - r-ggplot2 >=3.2.0
    - r-ggpubr >=0.2
    - r-httr
    - r-magrittr >=1.5
    - r-ppcor
    - r-psych
    - r-purrr
    - r-shiny >=1.3.2
    - r-stringr
    - r-tibble >=2.1.3
    - r-tidyr
    - r-ucscxenatools

  run:
    - gmp   # [linux]
    - mpfr  # [linux]
    - r-base
    - r-digest
    - r-dplyr >=0.8.3
    - r-ezcox
    - r-forcats
    - r-ggplot2 >=3.2.0
    - r-ggpubr >=0.2
    - r-httr
    - r-magrittr >=1.5
    - r-ppcor
    - r-psych
    - r-purrr
    - r-shiny >=1.3.2
    - r-stringr
    - r-tibble >=2.1.3
    - r-tidyr
    - r-ucscxenatools

test:
  commands:
    - $R -e "library('UCSCXenaShiny')"           # [not win]
    - "\"%R%\" -e \"library('UCSCXenaShiny')\""  # [win]

about:
  home: https://openbiox.github.io/UCSCXenaShiny/
  dev_url: https://github.com/openbiox/UCSCXenaShiny
  license: GPL-3.0-or-later
  summary: Provides functions and a Shiny application for downloading, analyzing and visualizing datasets from UCSC Xena (<http://xena.ucsc.edu/>), which is a collection of UCSC-hosted public databases such as TCGA, ICGC, TARGET, GTEx, CCLE, and others.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - Byronxy
    - conda-forge/r
    - kaigu1990
    - lishensuo
    - longfei8533
    - ShixiangWang
